### ISSUE TITLE
Unable to load /bundle.js from initrd.

### ISSUE THREAD

**Issue by SpaceboyRoss01** [runtimejs/runtime#104]
This is what I got:
`Unable to load /bundle.js from initrd.`
`Kernel error: abort() requested`

**Comment by facekapow** [comment]
Did you remember to `require('runtimejs')`?

**Comment by facekapow** [comment]
@SpaceboyRoss01 Seeing as how you're asking about other things that are OS functions and this is a startup problem, is it safe to assume this is resolved and can be closed?
