### ISSUE TITLE
Terminal will not work

### ISSUE THREAD

**Issue by SpaceboyRoss01** [runtimejs/runtime#109]
Hello, my os's terminal is not working. Every time I run a command, it doesn't put back up the prompt.
[Code](https://github.com/SpaceboyRoss01/basicos/blob/alpha/system/system/index.js)

**Comment by iefserge** [comment]
@SpaceboyRoss01 it's hard to say without seeing isolated test case. But looks like you aren't calling the command callback.

**Comment by iefserge** [comment]
Closing for now, let me know if that issue is still present.
