### ISSUE TITLE
Runtime can't load

### ISSUE THREAD

**Issue by SpaceboyRoss01** [runtimejs/runtime#112]
Whenever I load my os. I get this error:
Uncaught exception: __loader:26: Error: Cannot resolve module '/' from '/'
Error: Cannot resolve module '/' from '/'
    at Module.require (__loader:45:20)
    at Loader.require (__loader:247:25)
    at __loader:322:10
    at __loader:323:3

You can find the code here: https://github.com/SpaceboyRoss01/basicos

Here my package.json:
{
  "name": "basicos-alpha",
  "version": "0.0.1",
  "description": "The BasicOS written by Tross Software and Tech.",
  "main": "System/index.js",
  "dependencies": {},
  "devDependencies": {},
  "scripts": {
    "test": "npm version"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/SpaceboyRoss01/basicos.git"
  },
  "keywords": [
    "BasicOS"
  ],
  "author": "Tross Software and Tech",
  "license": "Apache-2.0",
  "bugs": {
    "url": "https://github.com/SpaceboyRoss01/basicos/issues"
  },
  "homepage": "http://www.basicos.ga/"
}

**Comment by iefserge** [comment]
@SpaceboyRoss01 I think the issue is that it can't find initial entry point file `index.js`.

**Comment by facekapow** [comment]
@SpaceboyRoss01 Is this resolved?

**Comment by SpaceboyRoss01** [comment]
yes
