### ISSUE TITLE
Date and Time

### ISSUE THREAD

**Issue by SpaceboyRoss01** [runtimejs/runtime#113]
I am wondering how I get the date and time in runtimejs.

**Comment by facekapow** [comment]
Just as you would with regular JavaScript, the [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) object.

**Comment by piranna** [comment]
Just curious, how is the data fetch internally?

**Comment by facekapow** [comment]
On boot, the time is fetched from CMOS, and when the JavaScript library is loaded, the time is requested from NTP. V8 automatically keeps track of time after it's set.

**Comment by piranna** [comment]
> V8 automatically keeps track of time after it's set.

That's what I was asking for, didn't know if it would do a syscall or other
mechanism to get the date, if the time progress is managed by V8 itself
then it's more powerful I though... Thanks! :-D

**Comment by facekapow** [comment]
No problem! :simple_smile:
