### ISSUE TITLE
Client and Server Problems

### ISSUE THREAD

**Issue by SpaceboyRoss01** [runtimejs/runtime#115]
I have an os using the eshttp library and I have it hosting a server, I can't connect to my server on my host pc. And The client doesn't see that a body exists.
I am listening to port 80 and port 8080.
Code: https://github.com/SpaceboyRoss01/basicos

**Comment by facekapow** [comment]
What port are you listening on? Because, unless you passed an extra `port` option to `runtime start`, the only port that passes from QEMU to the host is port 9000.

**Comment by facekapow** [comment]
Then instead of doing `runtime start`, you need to do `runtime start --port 80 --port 8080`.
(btw, you should probably add information by commenting, editing doesn't make any notifictions)

**Comment by SpaceboyRoss01** [comment]
This error shows up when I run `runtime start --port 80 --port 8080`:
`qemu-system-x86_64: -net user,net=192.168.76.0/24,dhcpstart=192.168.76.9,hostfwd=udp::9000-:9000,hostfwd=tcp::9000-:9000,hostfwd=udp::80-:80,hostfwd=tcp::80-:80,hostfwd=udp::8080-:8080,hostfwd=tcp::8080-:8080: could not set up host forwarding rule 'tcp::80-:80'
qemu-system-x86_64: -net user,net=192.168.76.0/24,dhcpstart=192.168.76.9,hostfwd=udp::9000-:9000,hostfwd=tcp::9000-:9000,hostfwd=udp::80-:80,hostfwd=tcp::80-:80,hostfwd=udp::8080-:8080,hostfwd=tcp::8080-:8080: Device 'user' could not be initialized`

**Comment by iefserge** [comment]
@SpaceboyRoss01 I think it needs sudo privileges for port 80. Does it start like this `runtime start --port 8080`?

**Comment by SpaceboyRoss01** [comment]
It works, but I can't connect to it in Firefox.

**Comment by iefserge** [comment]
Just tried this example https://github.com/runtimejs/example-web-server/blob/master/index.js using port 8080 and `runtime start --port 8080`. Worked for me. Are you sure you're setting up server correctly?

**Comment by SpaceboyRoss01** [comment]
close
