### ISSUE TITLE
Compilers

### ISSUE THREAD

**Issue by SpaceboyRoss01** [runtimejs/runtime#116]
I am working on my os, and I decided to start working on compilers. I need to know how to write a shell script compiler. Does anyone know how to?

**Comment by vitkarpov** [comment]
I'm sorry, maybe I don't understand something, but how does it relate to runtimejs? I mean, why do you ask it here?

**Comment by iefserge** [comment]
Yeah, let's discuss things that aren't directly related to runtime.js in discussions repo https://github.com/runtimejs/discussions or in Gitter chat https://gitter.im/runtimejs/runtime
