### ISSUE TITLE
Disk

### ISSUE THREAD

**Issue by SpaceboyRoss01** [runtimejs/runtime#117]
I am working on my os. I want to be able to access the disk to read and write to it. Does anyone know how to?

**Comment by iefserge** [comment]
@SpaceboyRoss01 unfortunately there is no disk driver in the system at the moment, so no way to access the disk. Discussion here https://github.com/runtimejs/runtime/issues/74

**Comment by SpaceboyRoss01** [comment]
So, I have to write the drivers myself?

**Comment by iefserge** [comment]
It can be done, but it's a pretty big task (needs VIRTIO-BLK driver, VFS, filesystem driver). For now runtime.js is more like diskless network system.

**Comment by SpaceboyRoss01** [comment]
I am working on a module, you can see the code on my git repository. The os uses 2 VFSs, 1 is the main hard disk, the other is written in json.

**Comment by iefserge** [comment]
Ah nice, I think the missing key component is VIRTIO-BLK driver to access the actual disk. I haven't looked into it much, but feel free to hack on it if you'd like, I might be able to help too. Disk support would definitely be a great addition to the system.

**Comment by SpaceboyRoss01** [comment]
@iefserge would you like to help me work on BasicOS?

**Comment by iefserge** [comment]
BLK driver and VFS can live in runtime.js repository. You'll be able to access filesystem the same way as in node
```js
require('fs').readFile(...)
```

**Comment by piranna** [comment]
But that would need the filesystems to be mounted somewhere, or that the
'fs' module do request to a VFS server that's the one that talks to the
hard disks, isn't it?

If It's not yet designed, I would prefer the second microkernel-like
alternative instead the first monolythic one. I know it would not be as
performant, but definitely it will be easier to design and develop and more
flexible.

**Comment by SpaceboyRoss01** [comment]
One VFS does, the other works on top of the other.

**Comment by iefserge** [comment]
Yeah, FS will talk to VFS. VFS will handle mounting and will have its own API.
There is no design yet, microkernel-like is basically running in a web worker. That would be awesome, provided performance is ok.

**Comment by piranna** [comment]
Sorry, I forgoy runtime.js has a single memory space... Then it would be trivial to design it microkernel-like and being still performant since message passing would be a single call to WebWorker.postMessage(), and at the same time it would be easy to test and use independently, I like it :-)
