### ISSUE TITLE
Help with compiling

### ISSUE THREAD

**Issue by SpaceboyRoss01** [runtimejs/runtime#119]
I am working on BasicOS and I am building the BOSS Script (BasicOS Servers). Here is the syntax
Open: <{
Close: }>

I need to know how to detect syntax and stuff.

**Comment by facekapow** [comment]
I'm pretty sure that's not as much of a straightforward as you think. Just Google ["writing a compiler"](https://www.google.com/search?q=writing%20a%20compiler) and see what you get ([the first result](http://programmers.stackexchange.com/questions/165543/how-to-write-a-very-basic-compiler) is pretty good). However, there are some good tools to help you do this in JavaScript, like [Jison](https://github.com/zaach/jison). Heck, even I wrote a [tiny, not useful at all, probably broken, just for fun language](https://github.com/facekapow/beauty-lang) with it (if I can do it, anyone can 😄 ).

But, this is definitely not the right place to ask. However, Google is your friend 😉 .
