### ISSUE TITLE
How to update V8 locally?

### ISSUE THREAD

**Issue by facekapow** [runtimejs/runtime#127]
I tried following `docs/v8_update.txt`, but it failed at `make x64.release i18nsupport=off` with:
```
make: *** No rule to make target `third_party/icu/icu.gypi', needed by `out/Makefile.x64.release'.  Stop.
```
I'm guessing that maybe it's outdated? How do I update V8 (I'm trying update to V8 5.4.245 just to try out async/await)? Do I have to use `gclient sync`?

Also, how do I update the list of source files in `deps/SConscript`? Manually?

**Comment by iefserge** [comment]
@facekapow async/await should already be in the current v8 behind the flag `--harmony-async-await`.

Re V8 update: I'm using a separate clean copy of v8 (checkout `<tag>`) and building it according to https://github.com/v8/v8/wiki/Building%20with%20Gyp. Then I copy generated files into runtime.js tree.
Yeah, pretty much updating `deps/SConscript` manually by searching and filtering all the *.cc files. Or by just compiling/linking and adding undefined references.

**Comment by facekapow** [comment]
Ahh... ok. I was assuming that the flag was `--harmony_async_await` (since it's always underscore separated in `node --v8-options`), sorry. Also useful information on how to update it in the future 👍 .
