### ISSUE TITLE
README.md example fails on "runtime start"

### ISSUE THREAD

**Issue by mjbright** [runtimejs/runtime#138]
I followed the example in the README.md, but it is failing at the "runtime start" step.
I'm running Fedora24, with node v4.6.1, npm v2.15.9

Note: I didn't explicitly install qemu unsure if this could conflict with VirtualBox on my system.
          I tried anyway and  see that qemu-system-x86_64 is invoked so I guess that's OK.

`          qemu-system-x86_64 --version
`
          tells me
           QEMU emulator version 2.6.2 (qemu-2.6.2-5.fc24), Copyright (c) 2003-2008 Fabrice Bellard

Below the output from runtime start.
What am I doing wrong?

```
> runtime start                                                                     
 --- starting qemu --- 
qemu-system-x86_64: -net user,net=192.168.76.0/24,dhcpstart=192.168.76.9,hostfwd=udp::9000-:9000,hostfwd=tcp::9000-:9000: could not set up host forwarding rule 'tcp::9000-:9000'
qemu-system-x86_64: -net user,net=192.168.76.0/24,dhcpstart=192.168.76.9,hostfwd=udp::9000-:9000,hostfwd=tcp::9000-:9000: Device 'user' could not be initialized

```

**Comment by facekapow** [comment]
That sort of error usually happens because you have something else running on port 9000. Could you check if there's something on port 9000 (via `sudo netstat -tulpn`)?

**Comment by mjbright** [comment]
Hah ... I was reading all the wrong parts of the error message ... thanks,
that was the problem.
