### ISSUE TITLE
Grub2 Can't find Multiboot header

### ISSUE THREAD

**Issue by SpaceboyRoss01** [runtimejs/runtime#140]
Hey, I'm using grub2 to boot runtime but Grub2 says that it can't find the multiboot header.

**Comment by piranna** [comment]
Do you know if runtime.js is a multiboot compliant kernel? Have you searched for the multiboot magic number? If not, it would be a good and somewhat easy addition :-)

**Comment by piranna** [comment]
Ok, it's multiboot compliant. So, when does your error shows up?

**Comment by SpaceboyRoss01** [comment]
when `multiboot /boot/runtime` is executed

**Comment by piranna** [comment]
Is that a command? How are you executing it?

**Comment by SpaceboyRoss01** [comment]
it is, Grub2 boot config source code:
```ini
set timeout=10
set color_highlight=black/white
set color_normal=green/black

function graphics() {
	loadfont /boot/unicode.pf2
	set gfxmode=1024x768
	set gfxpayload=keep
	terminal_output gfxterm
}

graphics()

menuentry "ModernOS" {
	loadfont /boot/unicode.pf2
	set gfxmode=1024x768
	set gfxpayload=keep
	terminal_output gfxterm
	multiboot /boot/runtime
	boot
}
```

**Comment by piranna** [comment]
How are you trying to exec it, on real hardware? Have you tried to run it on QEmu? It will be easier, you can be able to give it directly a multiboot kernel (I have done it myself in the past, also from scratch). Also, currently runtime.js only have drivers for virtio (virtual) devices...

**Comment by SpaceboyRoss01** [comment]
it works on qemu using the rom/kernel option

**Comment by piranna** [comment]
Ok, so seems it's an issue with Grub2. Have you tried syslinux? It's fairly easier to work with and install, in fact it's what I'm using in NodeOS.

**Comment by SpaceboyRoss01** [comment]
not yet

**Comment by piranna** [comment]
I would stick by the moment with the QEmu -kernel option, but if you are willing to use a bootloader, give syslinux a try ;-)

**Comment by SpaceboyRoss01** [comment]
I need help running syslinux to create a disk image from my disk directory

**Comment by piranna** [comment]
to create the disk image use `genfatfs`

**Comment by SpaceboyRoss01** [comment]
How do I get that command, I dont have it

**Comment by facekapow** [comment]
You could also use runtime-cli's  `mkimg` to generate a disk:
```bash
runtime mkimg --size <how big you want it (e.g. 10G for 10 gigabytes)> --label "MODERNOS" disk.img
```

**Comment by SpaceboyRoss01** [comment]
I found out that Grub2 doesn't have x64 support for non-linux kernels.

**Comment by SpaceboyRoss01** [comment]
I can design a bootloader and call it Runtime.js Boot Manager

**Comment by piranna** [comment]
It's better to fix multiboot support on runtime.js. Example code is easy to
understand, don't know why it's not working here...

**Comment by SpaceboyRoss01** [comment]
running readelf on the kernel outputs: `readelf: Error: Not an ELF file - it has the wrong magic bytes at the start`

**Comment by piranna** [comment]
grub accept elf kernels, but not only them... Why don't you try to compile
a hello world kernel, like the example one of grub multiboot spec? It's a
funny and instructive task :-)

**Comment by SpaceboyRoss01** [comment]
I got it to work now

**Comment by piranna** [comment]
congrats! :-)
