### ISSUE TITLE
Proposal: Update NPM package with latest version

### ISSUE THREAD

**Issue by austinfrey** [runtimejs/runtime#153]
It doesn't look like the `runtimejs` package includes the latest updates, namely references to `runtime.block.devices`. Any chance this can be pushed to NPM? I installed via github, but having it in the registry would be helpful. Thanks!

**Comment by iefserge** [comment]
Ah sorry, yeah I'll publish a new release to npm and github. Thank you!

**Comment by austinfrey** [comment]
@iefserge thanks!

**Comment by iefserge** [comment]
Released v0.2.16

**Comment by austinfrey** [comment]
awesome, thanks again
