### ISSUE TITLE
Proposal: Include JSConf '14 demo examples under the RuntimeJS github organization

### ISSUE THREAD

**Issue by austinfrey** [runtimejs/runtime#154]
@iefserge the demo examples, specifically the command line examples like `ls` and `echo` were really interesting. Any chance those could be added under the runtimeJS organization on GitHub?

**Comment by iefserge** [comment]
They were removed because runtime no longer attempts to implement Unix-like shell and utilities, instead they can be added as an external modules. It's a large chunk of work to fully implement those commands.
