### ISSUE TITLE
Electron Apps

### ISSUE THREAD

**Issue by dilan-omer** [runtimejs/runtime#158]
Hi there. Would Electron Apps be able to work with this, since it’s based on Linux?

**Comment by dilan-omer** [comment]
Ok, here’s my idea for it. Install electron through NPM. Create an electron app (which will be your GUI and renders since it’s based on Chromium). Write in your js loader to load the electron app as your main GUI.

Could this work?

**Comment by austinfrey** [comment]
@dilan-omer RuntimeJS is not based on Linux so you will probably face an uphill battle trying to get electron running on it. It is a completely new kernel built from scratch to run low-level javascript applications.

**Comment by dilan-omer** [comment]
Oh it's not based on Linux, or was that NodeOS. My bad
