### ISSUE TITLE
node.js compatibility

### ISSUE THREAD

**Issue by heapwolf** [runtimejs/runtime#3]
If an os built with runtimeJS could use npm or [`npmd`](https://github.com/dominictarr/npmd) as a package manager it would inherit a significant ecosystem of highly usable code. To do so it would need some degree of node.js compatibility. This issue could be a discussion thread for the idea. 

/cc @dominictarr @juliangruber @feross

**Comment by streamich** [comment]
@mikeal +1 for Node.js independent kernel
