### ISSUE TITLE
Add command history and scrolling to the shell

### ISSUE THREAD

**Issue by 5paceManSpiff** [runtimejs/runtime#38]

**Comment by iefserge** [comment]
@5paceManSpiff thank you for this feature request! unfortunately I wouldn't be able to get to this soon because runtime.js is currently under major rewrite (system design and code structure, going to split core into separate npm modules, also complexity of this system is insane, there is going to be a lot of structure changes and cleanups).

**Comment by piranna** [comment]
> going to split core into separate npm modules

Will runtime.js be managed by ```npm```? This would be awesome! :-D

**Comment by iefserge** [comment]
@piranna yeah, I think it would be nice to have different components available as npm modules and also be able to depend on other modules internally. Maybe even going to use browserify to make it simple to use.

It would look like this (not sure about exact module structure yet):
```js
var runtime = require('runtimejs-core');
var net = require('runtimejs-net')(runtime);
var fs = require('runtimejs-fs')(runtime);

// Use network directly
var socket = new net.UDPSocket();

// Http over network
var http = require('runtimejs-http')(net);

http.createServer( ... )

```

Also, all existing RRC/isolates/promises/pipes functionality is temporary going to be disabled. Just want to make it much much more simpler/less scalable and focus on critical stuff and get it running.

**Comment by piranna** [comment]
Cool! I've also done the NodeOS build system npm based, so maybe some day runtime.js would be a dependency! :-D

**Comment by iefserge** [comment]
Sounds great! :+1:

**Comment by iefserge** [comment]
Shell has been partially removed, because there is no filesystem and the idea is to not have shell at all by default.
