### ISSUE TITLE
Built-In Commands

### ISSUE THREAD

**Issue by ArielAbreu** [runtimejs/runtime#48]
How about some built-in, necessary shell commands? `help` (extremely needed), `echo` (really easy to impl.), `ping` (like the default `1`, but customizable), `clear`, `exit`/`shutdown`/`reboot` etc...

I've already been able to implement all of these except for `clear`.

I think they would be useful.

**Comment by iefserge** [comment]
@ArielAbreu yes, that would be a great idea to support some basic commands. There is no filesystem at the moment though (all code and files need to be bundled up using runtimeify), right now it's more like a network-only system (TCPSocket/UDPSocket are available).

**Comment by ArielAbreu** [comment]
So, as of now, would storing files in the cloud be suitable? For ex. Google Drive mounting?

**Comment by iefserge** [comment]
@ArielAbreu Should be possible to use FTP/HTTP to download or upload files. Other than that there is no local filesystem (might be added in a future though).

**Comment by piranna** [comment]
This could be a good use case for the [VFS](https://github.com/runtimejs/runtime/issues/1), here is not needed a block device and all the fs operations would be implemented as HTTP requests :-)

**Comment by ArielAbreu** [comment]
I'll try to work on this a bit, see what can be done as of now, and what could be done with some hacking, err, tweaking 😄.

**Comment by ArielAbreu** [comment]
PR #69 adds `poweroff` and `reboot`, the rest (except for `help`) are in `runtime-shell`. Closing this...
