### ISSUE TITLE
Modifier keys

### ISSUE THREAD

**Issue by ArielAbreu** [runtimejs/runtime#49]
Currently, the terminal input listens for keydown, which is fine, for now. But, for CTRL+C (and etc) to work, the terminal input should listen for keyup. It would require no change in input processing, just a change in listeners (unless you decide to implement modifiers). This is not a current issue, but could be in the future.

**Comment by iefserge** [comment]
@ArielAbreu There is a keyboard object that emits raw keyup/keydown events that include modifier keys as well. Shell could use this to implement CTRL+C feature. https://github.com/runtimejs/runtime/blob/master/js/core/keyboard/index.js
