### ISSUE TITLE
Running the tests

### ISSUE THREAD

**Issue by kesla** [runtimejs/runtime#50]
Hey, how do I run the js-tests? They require runtimejs like `require('runtimejs/core/net/tcp-socket')`(https://github.com/runtimejs/runtime/blob/master/js/test/net/tcp.js#L5) and not (as i would've expected) by their local file - so how do I run them?

**Comment by ArielAbreu** [comment]
What I did is I created a folder, copied the helloworld example's `package.json` and ran `npm install` and for each test I changed the start command's `runtimeify` file to the test file and ran `npm start`

**Comment by iefserge** [comment]
@kesla there needs to be a runner file that depends on runtimejs like
```
"dependencies": {
    "bar": "file:../foo/bar"
  }
```

**Comment by iefserge** [comment]
going to use postinstall script to avoid copying runtimejs on install
