### ISSUE TITLE
Runtimeify: Add extra files?

### ISSUE THREAD

**Issue by ArielAbreu** [runtimejs/runtime#51]
How do I embed extra, non-js files into the initrd created by runtimeify?
Can I add a folder? If runtimeify can't do this, can I edit the initrd manually and add it myself?

**Comment by iefserge** [comment]
@ArielAbreu it's possible to add files using Browserify https://www.npmjs.com/package/brfs transform. `-t` transform option needs to be exposed in runtimeify though.

**Comment by piranna** [comment]
What are the main differences between runtimeify y browserify? Maybe it
could be done as a browserify plugin or tranform...

**Comment by iefserge** [comment]
@piranna runtimeify will do more stuff in a future, like it's going to replace builtins with runtimejs's and bundle source maps in a way that's supported by runtime.
