### ISSUE TITLE
What happend to `/initrd`?

### ISSUE THREAD

**Issue by ArielAbreu** [runtimejs/runtime#52]
Uh, I see lots of useful Unix-like stuff in `/initrd/app` and `/initrd/driver` and `/initrd/system`?
What happend to it? Is it dead and deprecated? Can it be revived? Because they implement lots of basic system utils.

**Comment by iefserge** [comment]
@ArielAbreu it has been deprecated and the `initrd` directory is going to be removed. Most of the system and driver stuff has already been moved to `js` directory.
The isolates and the Unix-like apps are no longer supported, there are a few reasons for that:
- the isolates and RPC add a lot of complexity and at the same time could reduce performance, it would be much easier to get to the first stable release without this. Isolates are probably going to be added back later and exposed as Web Workers, the idea is that it's up to user to decide what code needs to be isolated in a web worker.
- Unix utilities and shell are needed when the system and applications running on top are separate entities. runtime.js bundles up all code into a single image and changes to application or system code require image to be recompiled and redeployed. This is similar to the concept of immutable servers that are always in predictable state.
- there is no filesystem that is necessary for shell utilities to work. FS is probably going to be added later though.

**Comment by ArielAbreu** [comment]
OK, thanks. I was wondering so I wouldn't have to build shell commands myself.
