### ISSUE TITLE
runtime.tty.print(): little problem

### ISSUE THREAD

**Issue by ArielAbreu** [runtimejs/runtime#53]
This is an issue I discovered while working with `runtime-node-net`. runtime's `runtime.tty.print()` function only accepts strings. You'd at least expect an error when given something else, but no. I tried printing an integer an nothing happened, no errors, nothing. Calling `toString()` on the number printed it. So I propose that the function should call `toString()` on the argument, which i'm believe is what `console.log()` does.

**Comment by iefserge** [comment]
:+1: ah yeah, sorry, you're right, it needs to call `String(text)` internally. I can fix this now or would you like to open a PR?

**Comment by ArielAbreu** [comment]
PR? Yeah.

**Comment by ArielAbreu** [comment]
Ok, Pull Request submitted.

**Comment by piranna** [comment]
> it needs to call String(text) internally

Really? I think it's a waste of resources to create a String object instead of calling the .toString() method to get the string literal representation...

**Comment by iefserge** [comment]
@piranna String(obj) is the same as obj.toString(), but also converts primitive values like null and undefined

**Comment by piranna** [comment]
:+1:
