### ISSUE TITLE
Reference Error: setImmediate is not defined

### ISSUE THREAD

**Issue by ArielAbreu** [runtimejs/runtime#63]
I think commit d26617b1cbe7ea3517e130eb8b5caf6740303382 broke TCP. I tried to use http.get (now that runtimeify supports runtime-net-node and http-node) and it gave the error in the title. I saw it in the commit but didn't see it get defined anywhere in the file. Pretty sure this should be fixed.

**Comment by iefserge** [comment]
@ArielAbreu hm, weird, it should be polyfilled here https://github.com/runtimejs/runtime/blob/master/js/core/polyfill.js#L18

**Comment by ArielAbreu** [comment]
I must have missed that. I just copy pasted the updated `tcp-socket.js` to my `node_modules/runtimejs`. Hmm, should've `git pull`'ed and later copied the `js` folder. My fault.
