### ISSUE TITLE
runtime.shell.runCommand(): Not using args in object parameter

### ISSUE THREAD

**Issue by ArielAbreu** [runtimejs/runtime#67]
When you pass an object as the second parameter to `runCommand`, the args option in it is not used. I believe the problem is in `/js/service/shell/index.js`, line 39 (https://github.com/runtimejs/runtime/blob/master/js/service/shell/index.js#L39), where it rests the args parameter. Maybe instead of `opts.args = [];`, it could be `opts.args = opts.args || [];`. I'm pretty sure that's the problem, because I changed it (in my clone of the repo) and it worked as it should.

**Comment by piranna** [comment]
Besides an argv-like array, it could be an object so command line args parsing is not needed :-)

**Comment by ArielAbreu** [comment]
You have a point. I''m just reporting an issue that I saw. But object params <i>would</i> make it easier for applications to get their parameters.

**Comment by piranna** [comment]
I have just got the idea when I saw your issue, that's all :-P

**Comment by iefserge** [comment]
Yep, this looks like a bug.

**Comment by ArielAbreu** [comment]
I didn't see it in my PR. Notoced it after it merged.
