### ISSUE TITLE
crypto.randomBytes: not support by this browser

### ISSUE THREAD

**Issue by ArielAbreu** [runtimejs/runtime#70]
I know there are a lot of things that `runtime` needs to be able to do that it can't, so I understand if this is set aside for later, but i'll continue with my problem anyway. When using `crypto.randomBytes` or `crypto.pseudoRandomBytes`, I get an error saying that it's not supported by this browser. I know Node.js uses OpenSSL to provide the function. Could I maybe compile OpenSSL with Emscripten and use the function from it?

**Comment by piranna** [comment]
> Could I maybe compile OpenSSL with Emscripten and use the function from it?

It's possible, but I would use a pure Javascript implementation of that algorythms if available, probably it would perfom better. Anyway, I would consider if OpenSSL could be integrated in runtime.js core itself...

**Comment by ArielAbreu** [comment]
Happen to know where the algorithms are :-)?

**Comment by piranna** [comment]
Probably they are documented ;-) There are several pure Javascript implementations of sha & friends :-)

**Comment by ArielAbreu** [comment]
I couldn't find the algorithm for random bytes anywhere, so I tried compiling OpenSSL with Emscripten, and it worked. But, I believe that (as you pointed out) it is better to add OpenSSL to the runtime.js core. I know Node uses OpenSSL, so it's likely it can also be done for runtime.js.

**Comment by iefserge** [comment]
Do you think we should compile in native OpenSSL or use the js version? Emscripten compiled OpenSSL should be pretty fast because of asm.js I guess.
One related issue is that runtime doesn't have any good random source, need to use virtio-rng http://wiki.qemu-project.org/Features-Done/VirtIORNG

**Comment by piranna** [comment]
> I know Node uses OpenSSL, so it's likely it can also be done for
runtime.js.

That was just the reason why I proposed to compile it in runtime.js core
:-) I admit is not a fundamental OS functionality, but I don't know of any
other place where to put it... :-/

**Comment by kesla** [comment]
I think that we should have a crypto library bundle together with runtimejs, but perhaps it would make sense to take a look at sodium (https://github.com/jedisct1/libsodium) as an alternative to openssl? 

Here's a quick reasoning why sodium is better than openssl: https://github.com/dominictarr/sodium-browserify/issues/1

There are also em

**Comment by piranna** [comment]
As far as the APIs are compatible and if possible without needing to use internally some compatibility helper functions, I don't mind what's underlying :-)

**Comment by ArielAbreu** [comment]
Yeah, libsodium looks pretty good, but, maybe it's better to install the C version libsodium into the core, and add a JS API (because there are still some parts of libsodium missing in node-sodium).

**Comment by iefserge** [comment]
I'd say let's try to use JS version if possible. The issue with random bytes, is that we can easily make random source available to JS, but not C/C++, because virtio driver is written in JS. Btw, asm.js should be very well supported by V8 and unless there's a big performance issue I'd try to keep crypto in JS.

Checked out libsodium, looks like it supports Emscripten as well https://github.com/jedisct1/libsodium/blob/master/src/libsodium/randombytes/randombytes.c#L8-L10

**Comment by ArielAbreu** [comment]
Well, for randombytes in libsodium (and every SSL library) requires a random source. So I'll try to create a driver for VirtIORNG, and use that for libsodium (says that it supports custom randomness implementations).

**Comment by iefserge** [comment]
sounds good, ping me if you need any help.

**Comment by kesla** [comment]
Sounds great, very excited about this!

**Comment by ArielAbreu** [comment]
@iefserge I do have one question, how did you map the network device to the driver file?

**Comment by iefserge** [comment]
@ArielAbreu here's the code that loads network driver https://github.com/runtimejs/runtime/blob/master/js/driver/virtio/index.js#L24-L26. 
Virtio rng device subsystem ID = 4 http://ozlabs.org/~rusty/virtio-spec/virtio-0.9.5.pdf (Appendix F)

**Comment by ArielAbreu** [comment]
Thanks. Googling 'VirtIORNG' just gave me the QEMU page. I really should look harder :P

**Comment by kesla** [comment]
@ArielAbreu this is done, right?

**Comment by ArielAbreu** [comment]
Yep, forgot to close it!
