### ISSUE TITLE
Real Time Clock & CMOS

### ISSUE THREAD

**Issue by ArielAbreu** [runtimejs/runtime#76]
I know runtime.js keeps track of time because every time you get a `new Date()`, it's different. However, runtime always starts time at January 1, 1970 at 0:00:00. I know QEMU exposes a CMOS and RTC, so, is there a way to set the initial time in V8? Getting the time from the CMOS is easy, (http://wiki.osdev.org/CMOS#Reading_All_RTC_Time_and_Date_Registers) but I don't know how to set the time in runtimejs. Maybe in `deps/musl` I can `clock_settime`?

**Comment by iefserge** [comment]
V8 uses value in microseconds since January 1, 1970 for the Date(), at the moment it's simply time since boot https://github.com/runtimejs/runtime/blob/master/deps/v8/src/base/platform/time.cc#L345
I'm not sure if we should rely on CMOS though, would it be better to use some time server instead?

**Comment by ArielAbreu** [comment]
Yes (maybe something like NTP), but wouldn't it have to be done from C++? I believe a driver for the network would have to be made in C++ for that.

**Comment by ArielAbreu** [comment]
Or use a time server and fallback to CMOS when it's not available.

**Comment by iefserge** [comment]
Driver could be done in javascript as well, we can add native function to change time in v8.

**Comment by iefserge** [comment]
I feel like CMOS would just make it more complex, unless it needs to work without network connection, which I think is unlikely for the network-focused system.

**Comment by ArielAbreu** [comment]
As long as there's a correct time, I (personally) don't think it matters how, though, I always tend to use the easiest way. If you say CMOS is too complex, then NTP it is.

**Comment by iefserge** [comment]
Well, it's not that CMOS is complex, but it's extra platform-dependent code. Btw, I'm ok with CMOS, if you feel it's a good idea to support it.

**Comment by ArielAbreu** [comment]
I believe maybe it should be as a backup. Sometimes the servers goes down for maintenance. Then again, they always keep at least one operational, so maybe it's not necessary.

**Comment by ArielAbreu** [comment]
I do need to know where would be a good place to put JS-C++ helper functions.

**Comment by iefserge** [comment]
Most of them are here https://github.com/runtimejs/runtime/blob/master/src/kernel/native-object.cc

**Comment by ArielAbreu** [comment]
Thanks! I've been able to create a function that takes the time in milliseconds since 1970 and sets it as the base time and exposed it in JS (which accepts it as a string), plus another function that gets the base time + the time since boot in milliseconds and returns that as the time and that is what's read in Time::Now. Now to get the time from an NTP!

**Comment by ArielAbreu** [comment]
@iefserge How do I make a *proper* UDP request? This is my code (in `/js/core/set_time.js`):
```js
'use strict';

var resources = require('./resources');

var ip = new runtime.net.IP4Address('66', '7', '96', '2');

var data = new Uint8Array(48);
data[0] = 0x1B;
for (var i = 1; i < 48; i++) {
  data[i] = 0;
}

var socket = new runtime.net.UDPSocket();
socket.onmessage = function(u8) {
  console.log('hey2');
}

setTimeout(function() {
  socket.send(ip, 123, data);
  console.log('hey');
}, 1000);
```
Which just outputs:
```
hey
```

Am I doing this right?

**Comment by iefserge** [comment]
yeah, that should work. There is a `--netdump` option in `runtime-qemu` that logs all QEMU network activity. After that `runtime-qemu --print-netdump` prints it.

**Comment by ArielAbreu** [comment]
In the net dump I just see DHCP and `Who's at` requests, no UDP requests.

**Comment by iefserge** [comment]
You might want to try to send it a few times, there is no delivery guarantee even within runtime network stack. For example, it will drop outgoing UDP packets if there is no ARP entry in cache (Who's at response required to translate IP address -> MAC Address)

**Comment by ArielAbreu** [comment]
`while` loop, no. `for` loop, no. `if variable === null` call function again, no. And just copy-pasting a bunch of times doesn't do anything. I did see the *same* ip being requested every time I looped in the netdump. But it was a `Who-has 192.168.76.2`, which is the guest-to-host ip, right?

**Comment by ArielAbreu** [comment]
Nevermind! What that meant was that I had to `sudo ifconfig bridge0 192.168.76.2`, after that, it worked.

**Comment by kesla** [comment]
We need something else than ntp to assure that the time is correct when we start a script, I'd expect a file with just `console.log(new Date())` to write out a reasonable time & do it with as quick as possible (read: before it has synced with a server).

**Comment by iefserge** [comment]
@kesla yeah, in this case CMOS is going to be really useful. Hopefully QEMU/KVM initializes it nicely on startup using current Linux time, so we can read it immediately on startup.
@ArielAbreu what do you mean by the user? using shell command? My guess is that first UDP request always fails because cache is empty on startup. The second one after a few moments (up to a second) should be delivered. You'd probably want to retransmit any UDP request anyway, so this should not be an issue.

**Comment by ArielAbreu** [comment]
Well, NTP isn't going to work. For some reason, it *always* returns the *same* time. Plus, since it has to access the network and wait, and it's done with a callback (non-blocking), `require()`ing runtime.js and then `console.log(new Date())` returns 1970. I really think it'd be better to read the time from CMOS and use that.

**Comment by iefserge** [comment]
We would need NTP to keep time in sync. But yeah, probably a good idea to read initial time from CMOS (it's better than 1970).

**Comment by ArielAbreu** [comment]
I need to take a look at some NTP implementations (maybe Apple's Open Source impl.) and see how they handle the data they get back from NTP because, like I said, I always get different buffer responses but the same time from NTP.

**Comment by piranna** [comment]
There's a pure Javascript ntp library that I've been using for testing on
NodeOS, I think it's node-ntp or node-ntpclient or something similar...

**Comment by ArielAbreu** [comment]
@piranna You mean https://github.com/moonpyk/node-ntp-client? Yeah, I tried using some of it's processing code, but I always end up with the same time.

**Comment by piranna** [comment]
Yes, that's one, although I believe it was working correctly to me (I test it some time ago)... :-/

**Comment by ArielAbreu** [comment]
#80 and #77 have been merged, fixing this.
