### ISSUE TITLE
How to connect to host's localhost?

### ISSUE THREAD

**Issue by ArielAbreu** [runtimejs/runtime#86]
How can I connect to the host's localhost from the guest? I've tried guest forwarding, but no I've had luck. I have a server on my host and I need the guest to use it (I know the server works because I can interact with it from the host). Any ideas?

**Comment by ArielAbreu** [comment]
I'm closing this since @iefserge just responded on a PR I accidentally submitted.

**Comment by iefserge** [comment]
just in case anyone needs this I'll copy my response here

> you should be able to connect to host directly using ip 192.168.76.2 (in user networking mode this is the default ip qemu uses for the host). runtime gets this ip as a router address during DHCP configuration

**Comment by ArielAbreu** [comment]
Thanks, btw.
