### ISSUE TITLE
Installation on windows.

### ISSUE THREAD

**Issue by sasha240100** [runtimejs/runtime#87]
Hi there, I installed everything by instruction. I am using Qemu version 2.4, and when i starting project (runtime-playground run init.js) nothing popup. 

    'qemu-system-x86_64',
    '-m 512',
    '-smp 1',
    '-s',
    '-boot order=d',
    '-netdev user,id=mynet0,hostfwd=tcp::5555-:80',
    '-device rtl8139,netdev=mynet0,mac=1a:46:0b:ca:bc:7c',
    '-kernel ' + __dirname + '/kernel.bin',
    '-initrd ' + tempfile,
    '-serial stdio',
    '-localtime',
    '-M pc',

But when i change "-M pc" to "-M versatilepb" and run again, black window with title "QEMU" popups and nothing else happens. What is the problem?

**Comment by sasha240100** [comment]
Solved.

**Comment by iefserge** [comment]
@sasha240100 Looks like `runtime-playground` is out of date and no longer maintained, take a look at example here http://runtimejs.org/getting-started/ or https://github.com/runtimejs/helloworld.
Note: there is one known Windows issue is that QEMU output doesn't get redirected to console.

**Comment by sasha240100** [comment]
@iefserge, thank you. The problem was that i downloaded another pack and copied it to programfiles/qemu.

**Comment by iefserge** [comment]
@sasha240100 btw, just fixed QEMU output issue on Windows (in latest `runtime-tools` package)
