### ISSUE TITLE
Cannot resolve module?

### ISSUE THREAD

**Issue by facekapow** [runtimejs/runtime#92]
I tried out the new version of runtime with runtime-shell and it just crapped out (runtime-shell, I mean) under the previous version, it worked fine. The exact error is:
```
Error: Cannot resolve module './lib/ping.js' from '/index.js'
  at Module.require (__loader:45:20)
  at /node_modules/runtime-shell/index.js:52:40
  at module.exports (/node_modules/runtime-shell/index.js:33:5)
  at /index.js:4:38
  at /index.js:7:3
  at Module.require (__loader:73:9)
  at Loader.require (__loader:235:25)
  at __loader:257:10
  at __loader
```
***But***, when I changed the `'./lib/ping.js'` to `__dirname + '/lib/ping.js'`, it worked perfectly. I ran through the code and `console.log`ed every part that seemed it had something to with the path resolving and logs what it should until it gets to the `resolvePath` function, at which point `resolveFrom` becomes empty but before the function was called it was what it should be ('/node_modules/runtime-shell'). Any ideas why this is happening?

**Comment by iefserge** [comment]
@facekapow yep, this is a bug in the module loader. I'll fix soon. Thank you!

**Comment by iefserge** [comment]
@facekapow require issue is fixed, you may still get errors though because most Node.js builtin modules aren't supported yet https://github.com/runtimejs/runtime/pull/91

**Comment by facekapow** [comment]
I know, this isn't that though. I was trying to load my runtime-shell module which has no external dependencies, it just failed when requiring ping.js from lib. Thanks for the fix!
