### ISSUE TITLE
__loader:26: Error: Cannot resolve module 'runtimejs' from '/index.js'

### ISSUE THREAD

**Issue by AshleyWrench** [runtimejs/runtime#97]
Hey, So I downloaded the [Example-Web-Server](https://github.com/runtimejs/example-web-server) and follwed the steps in the readme.md. When running the application (and any application I make) I get:

```
--- starting qemu ---
Misaligned i/o to address 0000ffff with size 4 for memory region io
Uncaught exception: __loader:26: Error: Cannot resolve module 'runtimejs' from '/index.js'
Error: Cannot resolve module 'runtimejs' from '/index.js'
    at Module.require (__loader:45:20)
    at /index.js:14:48
    at /index.js:3:17
    at /index.js:14:3
    at Module.require (__loader:73:9)
    at Loader.require (__loader:235:25)
    at __loader:270:10
    at __loader:275:3
[ terminate thread (reason: refcount 0) ]
Kernel error: Assertion failed: !"main isolate exited" (src/kernel/thread.cc: TearDown: 117)
```

Sorry I can't be much help - I got bored and I'm just messing about - but thought you guys should know.

> **NOTE:** I'm using Windows 8 (ugh I know) so I don't know if it's the qemu build I'm using or the OS. [(qemu-w64-setup-20151216.exe)](http://qemu.weilnetz.de/w64/)

**Comment by iefserge** [comment]
@AshleyWrench thank you, looks like Windows-related issue. Going to look into it.

**Comment by soapdog** [comment]
Just to confirm that this is still happening and is not an isolated case. My machine is a Win10 Surface.

**Comment by AshleyWrench** [comment]
I'm unable to say at this time (moved back to Linux) and have not had a Issue.

**Comment by iefserge** [comment]
@AshleyWrench @soapdog thank you, this is fixed in the new CLI version `npm install runtime-cli@latest -g`
