### ISSUE TITLE
Adjust helloworld on the website

### ISSUE THREAD

**Issue by ravens** [runtimejs/runtime#99]
The website http://runtimejs.org is still using the deprecated runtimeify/runtime-tools approach instead of using runtime-cli npm package.

**Comment by iefserge** [comment]
Thank you, gonna update it.

**Comment by soapdog** [comment]
Yep, I lost two days on that one. The documentation was old and wouldn't work as written... 😢

**Comment by iefserge** [comment]
Ahh sorry, I'll try to find time this weekend to update it.

**Comment by iefserge** [comment]
Updated the website, thanks for the opened issue.
